### ISSUE TITLE
Fixed Header/Nav

### ISSUE THREAD

**Issue by willsower** [willsower/imamu-room-recipes#3]
Need to keep header and navigation fixed, and footer at bottom of screen on scroll

**Comment by Maxyee** [comment]
I tried to fix this issue. I am a beginner in open source contributions. However,I solved the project and attached the file here in this issue section
Just replace the code from the project directory /pages/index.js
[index.zip](https://github.com/willsower/imamu-room-recipes/files/6797121/index.zip)

**Comment by willsower** [comment]
Perfect! Just reviewed it, and it's great. Let me know if you're interested in contributing more. :)

**Comment by Maxyee** [comment]
Sure. I will do that in my free time. However, I am happy that my code worked!
